name: Build and Deploy

on:
    pull_request:
        branches: [ master ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                node-version: 12
            - run: yarn install
            - run: yarn build
            - run: yarn test

            - name: Push build to S3
              uses: VishalVijay14/aws-s3-sync-action@master
              with:
                access_key: AKIA5GZC3W4NBH6KHJVF
                secret_access_key: 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
                region: 'us-east-1'
                source: 'build'
                destination_bucket: aws-staticbucket01
                destination_prefix: ${{ secrets.DESTINATION_PREFIX }}
                exclude: '.git/*'
                delete: true
                quiet: false
